name: json2bv
description: A sample command-line application.
# version: 1.0.0
# homepage: https://www.example.com

dependencies:
  test: '^1.14.3'
  code_builder: '^3.2.1'
  recase: '^3.0.0'
  tuple: '^1.0.3'
#  path: ^1.4.1

dev_dependencies:
  build_runner: ^1.9.0
  build_web_compilers: ^2.10.0
